//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoGame
    {
        public int GameID { get; set; }
        public string GameTitle { get; set; }
        public string YearReleased { get; set; }
        public int DeveloperID { get; set; }
        public int PlatformID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Description { get; set; }
        public string IMG { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual StockStatus StockStatus { get; set; }
    }
}
